[build-system]
requires = ["scikit-build-core>=0.11", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "pyenki"
version = "0.0.1.alpha"
dependencies = [
  "numpy>=1.21",
]

[project.optional-dependencies]
all = [
  "moviepy>=2",
  "jupyter_rfb"
]
viewer = [
  "PySide6",
  "PyOpenGL"
]

[tool.scikit-build]
minimum-version = "build-system.requires"
cmake.define = {BUILD_TESTS = "OFF", BUILD_EXAMPLES = "OFF"}
install.components = ["pyenki"]
wheel.packages = ["python/pyenki"]
wheel.exclude = ["__pycache__"]