import numpy
import numpy.typing
from typing import Unpack, SupportsFloat, SupportsInt, Annotated, TypeAlias, TypedDict, NotRequired
from .pyenki import World, PhysicalObject

Vector: TypeAlias = Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]']
VectorLike: TypeAlias = Annotated[numpy.typing.ArrayLike, numpy.float64, '[2, 1]']
Image: TypeAlias = Annotated[numpy.typing.NDArray[numpy.uint8], '[n, m, 3]']

class CameraConfig(TypedDict):
    camera_position: NotRequired[VectorLike]
    camera_altitude: NotRequired[SupportsFloat]
    camera_yaw: NotRequired[SupportsFloat]
    camera_pitch: NotRequired[SupportsFloat]
    camera_is_ortho: NotRequired[bool]
    camera_reset: NotRequired[bool]

def cleanup() -> None: ...
def init(share: bool = ...) -> None: ...
def run(duration: SupportsFloat = ...) -> None: ...
def render(world: World, /, walls_height: SupportsFloat = ..., width: SupportsInt = ..., height: SupportsInt = ..., selected_object: PhysicalObject | None = ..., camera_position: VectorLike = ..., camera_altitude: SupportsFloat = ..., camera_yaw: SupportsFloat = ..., camera_pitch: SupportsFloat = ..., camera_is_ortho: bool = ..., camera_reset: bool = ...) -> Image: ...
def run_in_viewer(world: World, /, fps: SupportsFloat = ..., time_step: SupportsFloat = ..., factor: SupportsFloat = ..., helpers: bool = ..., walls_height: SupportsFloat = ..., duration: SupportsFloat = ..., camera_position: VectorLike = ..., camera_altitude: SupportsFloat = ..., camera_yaw: SupportsFloat = ..., camera_pitch: SupportsFloat = ..., camera_is_ortho: bool = ..., camera_reset: bool = ...) -> None: ...
def save_image(world: World, path: str, /, walls_height: SupportsFloat = ..., width: SupportsInt = ..., height: SupportsInt = ..., selected_object: PhysicalObject | None = ..., camera_position: VectorLike = ..., camera_altitude: SupportsFloat = ..., camera_yaw: SupportsFloat = ..., camera_pitch: SupportsFloat = ..., camera_is_ortho: bool = ..., camera_reset: bool = ...) -> None: ...

class WorldView:
    @property
    def camera_altitude(self) -> float: ...
    @camera_altitude.setter
    def camera_altitude(self, value: SupportsFloat) -> None: ...
    camera_is_ortho: bool
    @property
    def camera_yaw(self) -> float: ...
    @camera_yaw.setter
    def camera_yaw(self, value: SupportsFloat) -> None: ...
    @property
    def camera_pitch(self) -> float: ...
    @camera_pitch.setter
    def camera_pitch(self, value: SupportsFloat) -> None: ...
    @property
    def camera_config(self) -> CameraConfig: ...
    def update_camera_config(self, **config: Unpack[CameraConfig]) -> None: ...
    @property
    def camera_position(self) -> Vector: ...
    @camera_position.setter
    def camera_position(self, value: VectorLike) -> None: ...
    helpers: bool
    tracking: bool
    world: World | None
    def __init__(self, world: World = ..., fps: SupportsFloat = ..., update_world: bool = ..., time_step: SupportsFloat = ..., factor: SupportsFloat = ..., helpers: bool = ..., walls_height: SupportsFloat = ..., camera_position: VectorLike = ..., camera_altitude: SupportsFloat = ..., camera_yaw: SupportsFloat = ..., camera_pitch: SupportsFloat = ..., camera_is_ortho: bool = ..., camera_reset: bool = ...) -> None: ...
    def hide(self) -> None: ...
    def move_camera(self, target_position: VectorLike, target_altitude: SupportsFloat = ..., target_distance: SupportsFloat = ..., yaw: SupportsFloat | None = ..., pitch: SupportsFloat | None = ...) -> None: ...
    def point_camera(self, target_position: VectorLike, target_altitude: SupportsFloat = ..., position: VectorLike | None = ..., altitude: SupportsFloat | None = ...) -> None: ...
    def reset_camera(self) -> None: ...
    def save_image(self, arg0: str) -> None: ...
    def show(self) -> None: ...
    def start_updating_world(self, time_step: SupportsFloat = ..., factor: SupportsFloat = ...) -> None: ...
    def stop_updating_world(self) -> None: ...
    @property
    def image(self) -> Image: ...
    @property
    def walls_height(self) -> float: ...
    @property
    def pyside_widget(self) -> object: ...
    @property
    def pyqt_widget(self) -> object: ...
    @property
    def selected_object(self) -> PhysicalObject | None: ...
