import collections.abc
import enum
import numpy
import numpy.typing

from typing import SupportsInt, SupportsFloat, Annotated, ClassVar, TypeAlias, overload

Vector: TypeAlias = Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]']
VectorLike: TypeAlias = Annotated[numpy.typing.ArrayLike, numpy.float64, '[2, 1]']
Array1D: TypeAlias = Annotated[numpy.typing.NDArray[numpy.float64], '[n]']
Array2D: TypeAlias = Annotated[numpy.typing.NDArray[numpy.float64], '[n, m]']
IntArray1D: TypeAlias = Annotated[numpy.typing.NDArray[numpy.int64], '[n]']
Image: TypeAlias = Annotated[numpy.typing.NDArray[numpy.uint8], '[n, m, 3]']
Polygon: TypeAlias = collections.abc.Sequence[Vector]
ARGBImage: TypeAlias = Annotated[numpy.typing.NDArray[numpy.uint8], '[n, m, 4]']
ARGBImageLike: TypeAlias = Annotated[numpy.typing.ArrayLike, numpy.uint8, '[n, m, 4]']

class Color:
    black: ClassVar[Color] = ...  # read-only
    blue: ClassVar[Color] = ...  # read-only
    gray: ClassVar[Color] = ...  # read-only
    green: ClassVar[Color] = ...  # read-only
    red: ClassVar[Color] = ...  # read-only
    white: ClassVar[Color] = ...  # read-only
    lightgray: ClassVar[Color] = ...  # read-only
    darkgray: ClassVar[Color] = ...  # read-only
    lightred: ClassVar[Color] = ...  # read-only
    darkred: ClassVar[Color] = ...  # read-only
    lightgreen: ClassVar[Color] = ...  # read-only
    darkgreen: ClassVar[Color] = ...  # read-only
    lightblue: ClassVar[Color] = ...  # read-only
    darkblue: ClassVar[Color] = ...  # read-only
    lightyellow: ClassVar[Color] = ...  # read-only
    yellow: ClassVar[Color] = ...  # read-only
    darkyellow: ClassVar[Color] = ...  # read-only
    orange: ClassVar[Color] = ...  # read-only
    violet: ClassVar[Color] = ...  # read-only
    purple: ClassVar[Color] = ...  # read-only
    pink: ClassVar[Color] = ...  # read-only
    cyan: ClassVar[Color] = ...  # read-only
    a: float
    b: float
    components: tuple[float, float, float, float]
    g: float
    r: float
    def __init__(self, r: SupportsFloat = ..., g: SupportsFloat = ..., b: SupportsFloat = ..., a: SupportsFloat = ...) -> None: ...
    def threshold(self, limits: Color) -> None: ...
    def toGray(self) -> float: ...
    @overload
    def __add__(self, arg0: SupportsFloat) -> Color: ...
    @overload
    def __add__(self, arg0: Color) -> Color: ...
    def __eq__(self, arg0: object) -> bool: ...
    @overload
    def __iadd__(self, arg0: SupportsFloat) -> None: ...
    @overload
    def __iadd__(self, arg0: Color) -> None: ...
    def __imul__(self, arg0: SupportsFloat) -> None: ...
    @overload
    def __isub__(self, arg0: SupportsFloat) -> None: ...
    @overload
    def __isub__(self, arg0: Color) -> None: ...
    def __itruediv__(self, arg0: SupportsFloat) -> None: ...
    def __mul__(self, arg0: SupportsFloat) -> Color: ...
    def __ne__(self, arg0: object) -> bool: ...
    @overload
    def __sub__(self, arg0: SupportsFloat) -> Color: ...
    @overload
    def __sub__(self, arg0: Color) -> Color: ...
    def __truediv__(self, arg0: SupportsFloat) -> Color: ...

class DifferentialWheeled(Robot):
    left_wheel_target_speed: float
    right_wheel_target_speed: float
    wheel_speed_noise: float
    def reset_encoders(self) -> None: ...
    @property
    def left_wheel_encoder_speed(self) -> float: ...
    @property
    def left_wheel_odometry(self) -> float: ...
    @property
    def max_wheel_speed(self) -> float: ...
    @property
    def right_wheel_encoder_speed(self) -> float: ...
    @property
    def right_wheel_odometry(self) -> float: ...
    @property
    def wheel_axis(self) -> float: ...

class EPuck(DifferentialWheeled):
    def __init__(self, proximity: bool = ..., camera: bool = ..., scanner: bool = ...) -> None: ...
    def set_led_ring(self, value: bool) -> None: ...
    @property
    def camera_image(self) -> Array2D: ...
    @property
    def prox_distances(self) -> Array1D: ...
    @property
    def prox_values(self) -> Array1D: ...
    @property
    def scan(self) -> Array1D: ...

class Marxbot(DifferentialWheeled):
    scanner_range: float
    def __init__(self) -> None: ...
    @property
    def scanner_distances(self) -> Array1D: ...
    @property
    def scanner_image(self) -> Array2D: ...

class PhysicalObject:

    class Part:
        @overload
        def __init__(self, lx: SupportsFloat, ly: SupportsFloat, height: SupportsFloat) -> None: ...
        @overload
        def __init__(self, shape: collections.abc.Sequence[VectorLike], height: SupportsFloat, textures: collections.abc.Sequence[collections.abc.Sequence[Color]] = ...) -> None: ...
        def __eq__(self, arg0: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __ne__(self, arg0: object) -> bool: ...
        @property
        def height(self) -> float: ...
        @property
        def shape(self) -> list[Vector]: ...
        @property
        def textures(self) -> list[list[Color]]: ...
        def contains(self, point: VectorLike, tolerance: float = ...) -> bool: ...

    angle: float
    angular_speed: float
    collision_callback: collections.abc.Callable[[PhysicalObject, PhysicalObject], None]
    collision_elasticity: float
    color: Color
    control_step_callback: collections.abc.Callable[[PhysicalObject, SupportsFloat], None]
    touch_callback: collections.abc.Callable[[PhysicalObject, bool, int, float, float, float], None]
    dry_friction_coefficient: float
    name: str
    @overload
    def __init__(self, parts: collections.abc.Sequence[PhysicalObject.Part], mass: SupportsFloat, color: Color = ...) -> None: ...
    @overload
    def __init__(self, radius: SupportsFloat, height: SupportsFloat, mass: SupportsFloat, color: Color = ...) -> None: ...
    @overload
    def __init__(self, shape: collections.abc.Sequence[Vector], height: SupportsFloat, mass: SupportsFloat, color: Color = ..., textures: collections.abc.Sequence[collections.abc.Sequence[Color]] = ...) -> None: ...
    @overload
    def __init__(self, lx: SupportsFloat, ly: SupportsFloat, height: SupportsFloat, mass: SupportsFloat, color: Color = ...) -> None: ...
    @property
    def position(self) -> Vector: ...
    @position.setter
    def position(self, value: VectorLike) -> None: ...
    @property
    def velocity(self) -> Vector: ...
    @velocity.setter
    def velocity(self, value: VectorLike) -> None: ...
    viscous_friction_coefficient: float
    viscous_moment_friction_coefficient: float
    def control_step(self, time_step: SupportsFloat) -> None: ...
    def on_touch(self, state: bool, button: int, x: float, y: float, z: float) -> None: ...
    def touch(self, state: bool, button: int, x: float, y: float, z: float) -> None: ...
    @property
    def _interlaced_distance(self) -> float: ...
    @property
    def has_collided(self) -> bool: ...
    @property
    def height(self) -> float: ...
    @property
    def is_cylindric(self) -> bool: ...
    @property
    def mass(self) -> float: ...
    @property
    def moment_of_inertia(self) -> float: ...
    @property
    def radius(self) -> float: ...
    @property
    def uid(self) -> int: ...
    @property
    def world(self) -> World: ...
    @property
    def parts(self) -> list[PhysicalObject.Part]: ...
    def contains(self, point: VectorLike, tolerance: float = ...) -> bool: ...

class Robot(PhysicalObject):
    pass

class Thymio2(DifferentialWheeled):

    class Button(enum.Enum):
        CENTER = ...
        FORWARD = ...
        BACKWARD = ...
        LEFT = ...
        RIGHT = ...

    class IRCommEvent:
        @property
        def intensities(self) -> IntArray1D: ...
        @property
        def payloads(self) -> IntArray1D: ...
        @property
        def rx_value(self) -> int: ...

    prox_comm_enabled: bool
    prox_comm_tx: int
    button_touch_callback: collections.abc.Callable[[Thymio2, Button], None]
    leds_buttons: list[float]
    leds_circle: list[float]
    leds_prox: list[float]
    led_left_blue: float
    led_left_red: float
    led_right_blue: float
    led_right_red: float
    def __init__(self) -> None: ...
    @property
    def buttons(self) -> list[bool]: ...
    def on_button_touch(self, button: Button) -> None: ...
    def touch_button(self, button: Button) -> None: ...
    def set_led_bottom_left(self, red: SupportsFloat = ..., green: SupportsFloat = ..., blue: SupportsFloat = ...) -> None: ...
    def get_led_bottom_left(self) -> list[float]: ...
    def set_led_bottom_right(self, red: SupportsFloat = ..., green: SupportsFloat = ..., blue: SupportsFloat = ...) -> None: ...
    def get_led_bottom_right(self) -> list[float]: ...
    def set_led_buttons(self, index: SupportsInt, value: SupportsFloat) -> None: ...
    def set_led_circle(self, index: SupportsInt, value: SupportsFloat) -> None: ...
    def set_led_prox(self, index: SupportsInt, value: SupportsFloat) -> None: ...
    def set_led_top(self, red: SupportsFloat = ..., green: SupportsFloat = ..., blue: SupportsFloat = ...) -> None: ...
    def get_led_top(self) -> list[float]: ...
    @property
    def ground_values(self) -> Array1D: ...
    @property
    def prox_comm_events(self) -> list[IRCommEvent]: ...
    @property
    def prox_distances(self) -> Array1D: ...
    @property
    def prox_values(self) -> Array1D: ...
    @property
    def led_colors(self) -> numpy.typing.NDArray[numpy.float64]: ...

class World:
    class WallsType(enum.Enum):
        SQUARE = ...
        CIRCULAR = ...
        NONE = ...

    class GroundTexture:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, data: ARGBImageLike) -> None: ...
        @property
        def height(self) -> int: ...
        @property
        def width(self) -> int: ...
        def __buffer__(self, flags: int) -> memoryview: ...
        def __release_buffer__(self, view: memoryview) -> None: ...

    control_step_callback: collections.abc.Callable[[World, SupportsFloat], None]
    random_generator: numpy.random.Generator
    random_seed: int
    @overload
    def __init__(self, seed: SupportsInt = ...) -> None: ...
    @overload
    def __init__(self, lx: SupportsFloat, ly: SupportsFloat, walls_color: Color = ..., ground_texture: World.GroundTexture = ..., seed: SupportsInt = ...) -> None: ...
    @overload
    def __init__(self, radius: SupportsFloat, walls_color: Color = ..., ground_texture: World.GroundTexture = ..., seed: SupportsInt = ...) -> None: ...
    def add_object(self, object: PhysicalObject) -> None: ...
    def copy_random_generator(self, world: World) -> None: ...
    def remove_object(self, object: PhysicalObject) -> None: ...
    def run(self, steps: SupportsInt = ..., time_step: SupportsFloat = ..., physics_oversampling: SupportsInt = ..., termination: collections.abc.Callable[[World], bool] | None = ..., callback: collections.abc.Callable[[World], None] | None = ...) -> None: ...
    def step(self, time_step: SupportsFloat, physics_oversampling: SupportsInt = ...) -> None: ...
    @property
    def objects(self) -> list[PhysicalObject]: ...
    @property
    def robots(self) -> list[Robot]: ...
    @property
    def static_objects(self) -> list[PhysicalObject]: ...
    @property
    def radius(self) -> float: ...
    @property
    def lx(self) -> float: ...
    @property
    def ly(self) -> float: ...
    @property
    def walls_type(self) -> World.WallsType: ...
    @property
    def walls_color(self) -> Color: ...
    @property
    def ground_texture(self) -> World.GroundTexture: ...
    @property
    def has_ground_texture(self) -> bool: ...
    def get_ground_color(self, position: VectorLike) -> Color: ...
