import collections.abc
import numpy
import numpy.typing
import typing
from typing import Annotated, ClassVar, TypeAlias, overload

Vector: TypeAlias = Annotated[numpy.typing.NDArray[numpy.float64], '[2, 1]']
VectorLike: TypeAlias = Annotated[numpy.typing.ArrayLike, numpy.float64, '[2, 1]']
Array1D: TypeAlias = Annotated[numpy.typing.NDArray[numpy.float64], '[n]']
Array2D: TypeAlias = Annotated[numpy.typing.NDArray[numpy.float64], '[n, m]']
IntArray1D: TypeAlias = Annotated[numpy.typing.NDArray[numpy.int64], '[n, m]']
Image: TypeAlias = Annotated[numpy.typing.NDArray[numpy.uint8], '[n, m, 3]']
Polygon: TypeAlias = collections.abc.Sequence[Vector]
Part: TypeAlias = tuple[Polygon, typing.SupportsFloat] | tuple[Polygon, typing.SupportsFloat, collections.abc.Sequence[Color]]

class Color:
    black: ClassVar[Color] = ...  # read-only
    blue: ClassVar[Color] = ...  # read-only
    gray: ClassVar[Color] = ...  # read-only
    green: ClassVar[Color] = ...  # read-only
    red: ClassVar[Color] = ...  # read-only
    white: ClassVar[Color] = ...  # read-only
    a: float
    b: float
    components: tuple[float, float, float, float]
    g: float
    r: float
    def __init__(self, r: typing.SupportsFloat = ..., g: typing.SupportsFloat = ..., b: typing.SupportsFloat = ..., a: typing.SupportsFloat = ...) -> None: ...
    def threshold(self, limits: Color) -> None: ...
    def toGray(self) -> float: ...
    @overload
    def __add__(self, arg0: typing.SupportsFloat) -> Color: ...
    @overload
    def __add__(self, arg0: Color) -> Color: ...
    def __eq__(self, arg0: object) -> bool: ...
    @overload
    def __iadd__(self, arg0: typing.SupportsFloat) -> None: ...
    @overload
    def __iadd__(self, arg0: Color) -> None: ...
    def __imul__(self, arg0: typing.SupportsFloat) -> None: ...
    @overload
    def __isub__(self, arg0: typing.SupportsFloat) -> None: ...
    @overload
    def __isub__(self, arg0: Color) -> None: ...
    def __itruediv__(self, arg0: typing.SupportsFloat) -> None: ...
    def __mul__(self, arg0: typing.SupportsFloat) -> Color: ...
    def __ne__(self, arg0: object) -> bool: ...
    @overload
    def __sub__(self, arg0: typing.SupportsFloat) -> Color: ...
    @overload
    def __sub__(self, arg0: Color) -> Color: ...
    def __truediv__(self, arg0: typing.SupportsFloat) -> Color: ...

class DifferentialWheeled(Robot):
    left_wheel_target_speed: float
    right_wheel_target_speed: float
    wheel_speed_noise: float
    def reset_encoders(self) -> None: ...
    @property
    def left_wheel_encoder_speed(self) -> float: ...
    @property
    def left_wheel_odometry(self) -> float: ...
    @property
    def max_wheel_speed(self) -> float: ...
    @property
    def right_wheel_encoder_speed(self) -> float: ...
    @property
    def right_wheel_odometry(self) -> float: ...
    @property
    def wheel_axis(self) -> float: ...

class EPuck(DifferentialWheeled):
    def __init__(self, proximity: bool = ..., camera: bool = ..., scanner: bool = ...) -> None: ...
    def set_led_ring(self, value: bool) -> None: ...
    @property
    def camera_image(self) -> Array2D: ...
    @property
    def prox_distances(self) -> Array1D: ...
    @property
    def prox_values(self) -> Array1D: ...
    @property
    def scan(self) -> Array1D: ...

class IRCommEvent:
    @property
    def intensities(self) -> IntArray1D: ...
    @property
    def payloads(self) -> IntArray1D: ...
    @property
    def rx_value(self) -> int: ...

class Marxbot(DifferentialWheeled):
    scanner_range: float
    def __init__(self) -> None: ...
    @property
    def scanner_distances(self) -> Array1D: ...
    @property
    def scanner_image(self) -> Array2D: ...

class PhysicalObject:
    angle: float
    angular_speed: float
    collision_callback: collections.abc.Callable[[PhysicalObject, PhysicalObject], None]
    collision_elasticity: float
    color: Color
    control_step_callback: collections.abc.Callable[[PhysicalObject, typing.SupportsFloat], None]
    dry_friction_coefficient: float
    name: str
    @property
    def position(self) -> Vector: ...
    @position.setter
    def position(self, value: VectorLike): ...
    @property
    def velocity(self) -> Vector: ...
    @velocity.setter
    def velocity(self, value: VectorLike): ...
    viscous_friction_coefficient: float
    viscous_moment_friction_coefficient: float
    def control_step(self, time_step: typing.SupportsFloat) -> None: ...
    @property
    def _interlaced_distance(self) -> float: ...
    @property
    def has_collided(self) -> bool: ...
    @property
    def height(self) -> float: ...
    @property
    def is_cylindric(self) -> bool: ...
    @property
    def mass(self) -> float: ...
    @property
    def moment_of_inertia(self) -> float: ...
    @property
    def radius(self) -> float: ...
    @property
    def uid(self) -> int: ...
    @property
    def world(self) -> World: ...

class Robot(PhysicalObject):
    pass

class Thymio2(DifferentialWheeled):
    prox_comm_enabled: bool
    prox_comm_tx: int
    def __init__(self) -> None: ...
    def set_led_bottom_left(self, red: typing.SupportsFloat = ..., green: typing.SupportsFloat = ..., blue: typing.SupportsFloat = ...) -> None: ...
    def set_led_bottom_left_i(self, red: typing.SupportsInt = ..., green: typing.SupportsInt = ..., blue: typing.SupportsInt = ...) -> None: ...
    def set_led_bottom_right(self, red: typing.SupportsFloat = ..., green: typing.SupportsFloat = ..., blue: typing.SupportsFloat = ...) -> None: ...
    def set_led_bottom_right_i(self, red: typing.SupportsInt = ..., green: typing.SupportsInt = ..., blue: typing.SupportsInt = ...) -> None: ...
    def set_led_buttons(self, index: typing.SupportsInt, value: typing.SupportsFloat) -> None: ...
    def set_led_buttons_i(self, index: typing.SupportsInt, value: typing.SupportsInt) -> None: ...
    def set_led_circle(self, index: typing.SupportsInt, value: typing.SupportsFloat) -> None: ...
    def set_led_circle_i(self, index: typing.SupportsInt, value: typing.SupportsInt) -> None: ...
    def set_led_left_blue(self, value: typing.SupportsFloat) -> None: ...
    def set_led_left_blue_i(self, value: typing.SupportsInt) -> None: ...
    def set_led_left_red(self, value: typing.SupportsFloat) -> None: ...
    def set_led_left_red_i(self, value: typing.SupportsInt) -> None: ...
    def set_led_prox(self, index: typing.SupportsInt, value: typing.SupportsFloat) -> None: ...
    def set_led_prox_i(self, index: typing.SupportsInt, value: typing.SupportsInt) -> None: ...
    def set_led_right_blue(self, value: typing.SupportsFloat) -> None: ...
    def set_led_right_blue_i(self, value: typing.SupportsInt) -> None: ...
    def set_led_right_red(self, value: typing.SupportsFloat) -> None: ...
    def set_led_right_red_i(self, value: typing.SupportsInt) -> None: ...
    def set_led_top(self, red: typing.SupportsFloat = ..., green: typing.SupportsFloat = ..., blue: typing.SupportsFloat = ...) -> None: ...
    def set_led_top_i(self, red: typing.SupportsInt = ..., green: typing.SupportsInt = ..., blue: typing.SupportsInt = ...) -> None: ...
    @property
    def ground_values(self) -> Array1D: ...
    @property
    def ground_values_i(self) -> IntArray1D: ...
    @property
    def prox_comm_events(self) -> list[IRCommEvent]: ...
    @property
    def prox_distances(self) -> Array1D: ...
    @property
    def prox_values(self) -> Array1D: ...
    @property
    def prox_values_i(self) -> IntArray1D: ...

class World:
    control_step_callback: collections.abc.Callable[[World, typing.SupportsFloat], None]
    random_generator: numpy.random.Generator
    random_seed: int
    @overload
    def __init__(self, seed: typing.SupportsInt = ...) -> None: ...
    @overload
    def __init__(self, width: typing.SupportsFloat, height: typing.SupportsFloat, walls_color: Color = ..., seed: typing.SupportsInt = ...) -> None: ...
    @overload
    def __init__(self, radius: typing.SupportsFloat, walls_color: Color = ..., seed: typing.SupportsInt = ...) -> None: ...
    def add_object(self, object: PhysicalObject) -> None: ...
    def copy_random_generator(self, world: World) -> None: ...
    def remove_object(self, object: PhysicalObject) -> None: ...
    def render(self, camera_reset: bool = ..., camera_position: VectorLike = ..., camera_altitude: typing.SupportsFloat = ..., camera_yaw: typing.SupportsFloat = ..., camera_pitch: typing.SupportsFloat = ..., camera_is_ortho: bool = ..., walls_height: typing.SupportsFloat = ..., width: typing.SupportsFloat = ..., height: typing.SupportsFloat = ...) -> Image: ...
    def run(self, steps: typing.SupportsInt = ..., time_step: typing.SupportsFloat = ..., physics_oversampling: typing.SupportsInt = ..., termination: collections.abc.Callable[[World], bool] | None = ..., callback: collections.abc.Callable[[World], None] | None = ...) -> None: ...
    def run_in_viewer(self, fps: typing.SupportsFloat = ..., time_step: typing.SupportsFloat = ..., factor: typing.SupportsFloat = ..., helpers: bool = ..., camera_reset: bool = ..., camera_position: VectorLike = ..., camera_altitude: typing.SupportsFloat = ..., camera_yaw: typing.SupportsFloat = ..., camera_pitch: typing.SupportsFloat = ..., camera_is_ortho: bool = ..., walls_height: typing.SupportsFloat = ..., duration: typing.SupportsFloat = ...) -> None: ...
    def save_image(self, path: str, camera_reset: bool = ..., camera_position: VectorLike = ..., camera_altitude: typing.SupportsFloat = ..., camera_yaw: typing.SupportsFloat = ..., camera_pitch: typing.SupportsFloat = ..., camera_is_ortho: bool = ..., walls_height: typing.SupportsFloat = ..., width: typing.SupportsFloat = ..., height: typing.SupportsFloat = ...) -> None: ...
    def step(self, time_step: typing.SupportsFloat, physics_oversampling: typing.SupportsInt = ...) -> None: ...
    @property
    def objects(self) -> set[PhysicalObject]: ...
    @property
    def robots(self) -> list[Robot]: ...
    @property
    def static_objects(self) -> list[PhysicalObject]: ...

class WorldView:
    camera_altitude: float
    camera_is_ortho: bool
    camera_pitch: float
    camera_pose: tuple[float, float, float, float]
    @property
    def camera_position(self) -> Vector: ...
    @camera_position.setter
    def camera_position(self, value: VectorLike): ...
    camera_yaw: float
    helpers: bool
    tracking: bool
    world: World
    def __init__(self, world: World = ..., fps: typing.SupportsFloat = ..., update_world: bool = ..., time_step: typing.SupportsFloat = ..., factor: typing.SupportsFloat = ..., helpers: bool = ..., camera_reset: bool = ..., camera_position: VectorLike = ..., camera_altitude: typing.SupportsFloat = ..., camera_yaw: typing.SupportsFloat = ..., camera_pitch: typing.SupportsFloat = ..., camera_is_ortho: bool = ..., walls_height: typing.SupportsFloat = ...) -> None: ...
    def hide(self) -> None: ...
    def move_camera(self, target_position: VectorLike, target_altitude: typing.SupportsFloat = ..., target_distance: typing.SupportsFloat = ..., yaw: typing.SupportsFloat | None = ..., pitch: typing.SupportsFloat | None = ...) -> None: ...
    def point_camera(self, target_position: VectorLike, target_altitude: typing.SupportsFloat = ..., position: VectorLike | None = ..., altitude: typing.SupportsFloat | None = ...) -> None: ...
    def reset_camera(self) -> None: ...
    def save_image(self, arg0: str) -> None: ...
    def show(self) -> None: ...
    def start_updating_world(self, time_step: typing.SupportsFloat = ..., factor: typing.SupportsFloat = ...) -> None: ...
    def stop_updating_world(self) -> None: ...
    @property
    def image(self) -> Image: ...
    @property
    def walls_height(self) -> float: ...
    @property
    def widget(self) -> object: ...

def CircularObject(radius: typing.SupportsFloat, height: typing.SupportsFloat, mass: typing.SupportsFloat, color: Color = ...) -> PhysicalObject: ...
def CompositeObject(parts: list[Part], mass: typing.SupportsFloat, color: Color = ...) -> PhysicalObject: ...
def ConvexObject(base: collections.abc.Sequence[Vector], height: typing.SupportsFloat, mass: typing.SupportsFloat, color: Color = ..., face_colors: collections.abc.Sequence[Color] = ...) -> PhysicalObject: ...
def RectangularObject(l1: typing.SupportsFloat, l2: typing.SupportsFloat, height: typing.SupportsFloat, mass: typing.SupportsFloat, color: Color = ...) -> PhysicalObject: ...
def cleanup_ui() -> None: ...
def init_ui() -> None: ...
def run_ui(duration: typing.SupportsFloat = ...) -> None: ...
